#!/usr/bin/python3
import os
import sys
import json

if len(sys.argv) > 1:
    action = sys.argv[1]
else:
    sys.exit()

if len(sys.argv) > 2:
    socks = sys.argv[2]
else:
    sys.exit()

if len(sys.argv) > 3:
    value = sys.argv[4]
else:
    sys.exit()

limit = 10
if len(sys.argv) > 4:
    limit = int(sys.argv[4])
    
region = 'US'
if len(sys.argv) > 5:    
    region = sys.argv[5]

os.environ['SOCKS_PROXY'] = socks

if action == 'search':
    from youtubesearchpython import VideosSearch
    videosSearch = VideosSearch(query = value, limit = limit, region = region)
    print(json.dumps(videosSearch.result()))

if action == 'video':
    from youtubesearchpython import Video
    video = Video.getInfo(value, 0)
    print(json.dumps(video))
